version: "3"

services:
  sonarqube:
    image: sonarqube:8.2-community
    restart: always
    container_name: sonarqube
    hostname: sonarqube
    expose:
      - 9000
    user: "999"
    ports:
      - 9000:9000
    environment:
    - sonar.jdbc.username=sonar
    - sonar.jdbc.password=sonar
    - sonar.jdbc.url=jdbc:postgresql://db/sonar
    - sonar.search.javaAdditionalOpts=-Dbootstrap.system_call_filter=false
    volumes:
      - /home/diego/dockers/sonar/data_sonarqube/logs:/opt/sonarqube/logs
      - /home/diego/dockers/sonar/data_sonarqube/data:/opt/sonarqube/data
      - /home/diego/dockers/sonar/data_sonarqube/extension:/opt/sonarqube/extensions
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  db:
    image: postgres:12.0
    restart: always
    container_name: sonarqube-pg
    hostname: sonarqube-pg
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - /home/diego/dockers/sonar/data_postgresql:/var/lib/postgresql
      - /home/diego/dockers/sonar/data_postgresql/data:/var/lib/postgresql/data